steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/quotesearcher/gcr.io/quotesearcher/github.com/maksym-ma/quotesearcher:latest', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/quotesearcher/gcr.io/quotesearcher/github.com/maksym-ma/quotesearcher:latest']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'quotesearcher', '--image', 'gcr.io/quotesearcher/gcr.io/quotesearcher/github.com/maksym-ma/quotesearcher:latest', '--region', 'europe-north1', '--platform', 'managed']
images:
  - gcr.io/quotesearcher/gcr.io/quotesearcher/github.com/maksym-ma/quotesearcher:latest